// Fluxo de busca como um usuário: cidade → local → seção → Confirma; e o atalho zona + seção.
import { chromium } from "playwright-core";
const BASE = process.argv[2] || "http://127.0.0.1:4195";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const erros = [];
p.on("pageerror", (e) => erros.push(String(e)));
await p.goto(BASE + "/", { waitUntil: "networkidle" });
await p.fill("#cidade", "brasil");
await p.waitForSelector("#lista-cidade li[id]");
console.log("cidades:", await p.$$eval("#lista-cidade li[id] .t", (l) => l.map((x) => x.textContent).slice(0, 3)));
await p.keyboard.press("Enter");
await p.waitForSelector("#campo-local:not([hidden])");
await p.fill("#local", "102 sul");
await p.waitForSelector("#lista-local li[id]");
console.log("locais:", await p.$$eval("#lista-local li[id] .t", (l) => l.map((x) => x.textContent).slice(0, 3)));
await p.click("#lista-local li[id]");
await p.waitForSelector("#campo-secao:not([hidden])");
const chips = await p.$$eval(".chip", (l) => l.map((x) => x.textContent));
console.log("seções:", chips.join(" "));
await p.click(".chip >> nth=1");
await p.screenshot({ path: "tests/shots/fluxo-busca.png" });
await p.click("#confirma");
await p.waitForSelector("#resultado:not([hidden]) .r2-linha");
console.log("manchete:", await p.textContent("#manchete"), "| hash:", await p.evaluate(() => location.hash));
await p.click("#voltar");
await p.click("#corrige");
await p.fill("#cidade", "rio branco");
await p.waitForSelector("#lista-cidade li[id]");
await p.keyboard.press("Enter");
await p.waitForSelector("#campo-local:not([hidden])");
await p.click("#sei-secao");
await p.fill("#zona", "1");
await p.fill("#secao", "686");
await p.click("#confirma");
await p.waitForSelector("#resultado:not([hidden]) .r2-linha", { timeout: 5000 }).catch(() => erros.push("zona+seção não abriu: " + location.hash));
console.log("AC:", await p.textContent("#manchete"), "|", (await p.textContent("#explica")).slice(-90));
await p.screenshot({ path: "tests/shots/fluxo-ac.png", fullPage: true });
const dl = p.waitForEvent("download", { timeout: 8000 }).catch(() => null);
await p.click("#baixar");
const d = await dl;
if (d) { await d.saveAs("tests/shots/stories.png"); console.log("stories ok"); } else erros.push("stories não baixou");
console.log(erros.length ? erros : "sem erros");
await b.close();
